apiVersion: v1
kind: PersistentVolume
metadata:
  name: php-httpd-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/code"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-httpd-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: manual
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: php-httpd-service
spec:
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 80
  selector:
    app: php-httpd
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: php-httpd
  name: php-httpd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-httpd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: php-httpd
    spec:
      containers:
      - image: docker.io/credulous/php-httpd:dev
        name: php-httpd
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: "/var/www"
          name: php-httpd-docroot
      initContainers:
      - image: docker.io/credulous/fedora:37
        name: code-deploy
        volumeMounts:
        - mountPath: "/var/www"
          name: php-httpd-docroot
        command:
        - 'sh'
        - '-c'
        - 'rm -rf /var/www/* && git clone https://github.com/credulous67/safe_mgmt_code.git /var/www'
      restartPolicy: Always
      volumes:
      - name: php-httpd-docroot
        persistentVolumeClaim:
          claimName: php-httpd-claim
status: {}
