version: '3'

services:
  fedora:
    build:
      context: ./fedora
    networks:
      - frontend
      - backend

# Build of php_httpd required fedora
  php_httpd:
    build:
      context: ./php_httpd
    networks:
      - frontend
      - backend
    ports:
      - 8080:80
    volumes:
      - "./DocumentRoot:/var/www/html:Z,ro"

# Build of db_seeder required fedora
# db_seeder checks if database is empty, and if so, seeds it with initial schema & data
  db_seeder:
    build:
      context: ./db_seeder
    depends_on:
      - mariadb
    networks:
      - frontend
      - backend

  mariadb:
    image: mariadb:10
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - mariadb-volume:/var/lib/mysql
    environment:
      TZ: "Europe/London"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "rootpwd"
      MYSQL_USER: '_svc_sm'
      MYSQL_PASSWORD: 'smpass'
      MYSQL_DATABASE: 'safe_mgmt'

  phpmyadmin:
    image: phpmyadmin:5-apache
    networks:
      - frontend
      - backend
    depends_on:
      - mariadb
    restart: unless-stopped
    environment:
      PMA_HOST: "mariadb"
    ports:
      - 8081:80


volumes:
    mariadb-volume:

networks:
  frontend: {}
  backend: {}
